#!/bin/bash -e

source $OPENSHIFT_CARTRIDGE_SDK_BASH

list=
kvargs=$(echo "${@:4}" | tr -d "\n" )
for arg in $kvargs; do
    ip=$(echo "$arg" | cut -f 2 -d '=' | tr -d "'")
    if [ -z "$list" ]; then
        list="$ip"
    else
        list="$list\n$ip"
    fi
done

echo -e $list > $OPENSHIFT_HAPROXY_DIR/conf/app_haproxy_status_urls.conf
