#!/bin/bash

# Publishes the postgresql database connection information.

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Publish postgresql database connection information"

    echo "$0 $@" | logger -p local0.notice -t stickshift_postgresql_publish_conn_info
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done


[ $# -eq 3 ] || print_help

source /etc/stickshift/stickshift-node.conf
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

for v in `ls $GEAR_BASE_DIR/$3/.env/OPENSHIFT_POSTGRESQL_DB*`
do
    app_remove_env_var $v
done
