#!/bin/bash
#
# openshift-port-proxy
#
# chkconfig:   345 85 15
# description: OpenShift proxy
# processname: node-supervisor
# config:      /etc/openshift/port-proxy.cfg
# pidfile:     /var/run/node-web-proxy.pid

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

nodeserver="/root/server.js"
cmd="node-supervisor -w $nodeserver node $nodeserver"
prog=node-web-proxy
lockfile=/var/lock/subsys/node-web-proxy
pidfile=/var/run/node-web-proxy-supervisor.pid
childpidfile=/var/run/node-web-proxy.pid
cfgfile=/etc/openshift/node-web-proxy.cfg
logfile=/var/log/node-web-proxy.log

start() {
    echo -n $"Starting node-web-proxy: "
    nohup $cmd &> $logfile &
    echo $! > $pidfile
    retval=$?
    [ $retval -eq 0 ] && touch $lockfile && echo_success
    return $retval
}

stop() {
    echo -n $"Stopping node-web-proxy: "
    killproc -p $pidfile $prog 
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    echo -n $"Reloading node-web-proxy: "
    childpid=$(<$childpidfile)
    kill -HUP $childpid
    retval=$?
    echo
    return $retval
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    reload)
        reload
        ;;
    status)
        status -p $pidfile $prog
        ;;
    condrestart|try-restart)
  	if [ -f $lockfile ] 
        then
            restart
        fi
	;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|reload}"
        exit 2
esac
